-- Create databases
CREATE DATABASE todo;
CREATE DATABASE twitter;

-- Create users with passwords
CREATE USER todo WITH PASSWORD 'todo';
CREATE USER twitter WITH PASSWORD 'twitter';

-- Grant privileges on todo database to todo user
GRANT CONNECT ON DATABASE todo TO todo;
GRANT CREATE ON DATABASE todo TO todo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO todo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO todo;
\c todo
GRANT ALL PRIVILEGES ON SCHEMA public TO todo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO todo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO todo;

-- Grant privileges on twitter database to twitter user
GRANT CONNECT ON DATABASE twitter TO twitter;
GRANT CREATE ON DATABASE twitter TO twitter;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO twitter;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO twitter;
\c twitter
GRANT ALL PRIVILEGES ON SCHEMA public TO twitter;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO twitter;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO twitter;
