name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev, feat/gtd]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            test_apps -> target

      - name: Format check
        run:  make fmt

      - name: Check workspace
        run: make check

      - name: Test workspace
        run: make test
